### PR TITLE
Fixing php warning/errors while loading product editor

### PR DESCRIPTION
**Pull request by Just-m**

### CODE REVIEW

**Comment by PurpleVsGreen** [comment]
Thank you for this effort. You appear to have fixed some of the issues I'm having.

I'd like to test these changes, but it says ``unknown repository`` on top(?). What branch of your fork should I merge?

**Comment by Just-m** [comment]
Not sure these are in a brand any longer. I used to just refork and add commits online when I wanted to suggest changes. Only recently started keeping score using Windows Gitthub and creating branches.

**Comment by PurpleVsGreen** [comment]
Hi!

Mind if I create a new PR?

**Comment by Just-m** [comment]
If it needs re-submitting I might as well do it myself.

**Comment by PurpleVsGreen** [comment]
Alright, thank you. I did some things differently though, as outlined in #3454. Did I do it wrong? Due to my limited knowledge of this code base, I have no idea which diffs would be best or if we've both err'd. Hopefully with a little help from the maintainer we can reach consensus on what solutions would be best(?) Not that I don't appreciate your effort here, that would be silly.

**Pull request closed without merging**
