### PR TITLE
Simplify name copying in address script.

### PR DESCRIPTION
**Pull request by clifgriffin**
The fix in #3195 introduced complexities that have caused bugs in our install. 

In some instances, maybe 10% of the time, we're seeing a shipping or billing name like this:
SmithPerryPerry D. Smith

Our form has some uniqueness, including the fact that the shipping name field is before the first, last name fields. However, the billing name is also affected in nearly all cases.

The code for the fix in #3195 is very complex and I think will consequently be difficult to maintain or debug. Consequently, I stripped down the logic to this:

If either first or last name is changed AND both first and last name have values, set billing name and shipping name if they don't already have values.

### CODE REVIEW

**Comment by clifgriffin** [comment]
@ben72 Can you test this?

**Comment by clifgriffin** [comment]
@jonathandavis We've had this code live on a couple of client sites for 6 weeks now, with no more buggy issues. 

It'd be good to have someone else test this on a standard install before we merge, but I think the simplified logic is working well.

**Comment by jonathandavis** [comment]
This patch as is essentially reverts to the previous state of the code with the added empty fields check. It does make me sad that the complex algorithm was dumped instead of improved. It had the benefit of changing only the billing/shipping name that matched the previously entered first and last name fields. So if you changed the first/last name it would change the matching billing/shipping name. If the billing/shipping name didn't match the entered name, it would preserve the current name. Obviously at times buggy, but at 10% it wasn't far off the mark for a nice bit of data entry convenience.

**Comment by clifgriffin** [comment]
Ah, that's interesting. To be honest, neither @msigley or I 100% understood that that was the intended behavior behind the data-last stashing. 

This being said, I still prefer simple and foolproof to clever. So I'd still vote we sacrifice that feature in the name of making sure this works for reliably for all users and installs.

**Pull request merged**
