### PR TITLE
Password reset workflow changes and error message fixes.

### PR DESCRIPTION
**Pull request by msigley**
This changes the Password Reset workflow to help eliminate customer frustration.
The need to view the contents of the 2nd email is completely eliminated by auto logging in the customer after the reset key is verified and multiple reset requests in an hour timeframe will now send out the same activation key to eliminate problems from customers doing a bunch of reset requests in a row.

### CODE REVIEW

**Comment by msigley** [comment]
Addresses some of #2992 and #3295.

**Comment by crunnells** [comment]
I'm gonna see if we can merge these changes into the 1.3.x branch.

**Comment by sierrab123** [comment]
@crunnells There is a 1312 dev branch that was started a few weeks back

**Comment by crunnells** [comment]
Yeah I'm gonna pull that down and merge locally. I've got a client that needs this badly. I'll let you know how it goes.

**Comment by meredevelopment** [comment]
@crunnells My client also needs something done about the forgotten password process, still. I've taken a look at the current 1.4 dev branch ('master' at the moment I think) and some of @msigley work is still there, waiting to be finished off. I'm particularly interested in [this line](https://github.com/ingenesis/shopp/blob/master/core/flow/Pages.php#L594) that suggests that a way to SET a pass, and not just have it set for you is present. 

Here's basically what I'd like to see for my client, and if we can all agree on something similar to this that works across the board that would be great! : 

- Not having the password sent in plain text. We've gotten into trouble for it. 
- Having a strong pass suggested during the reset process, but having the ability to set on. Much like the way that WP code does it currently. 
- Reducing the number of steps to a successful password reset. 

This probably needs to become an 'issue' with some PR's hanging off it, but I'm starting the ball rolling again here as there's some history above. 

Whaddayareckon?

**Comment by msigley** [comment]
@meredevelopment: The changes here handle everything you mentioned except not emailing the customer their password. When I was writing this I emulated most of the password reset process from twitter.com which did in 2015 email you an auto-generated password and auto-login the user on a successful reset. I pointed the auto-login to redirect the user to the "edit account" page by default, which provides the user the ability to set a password of their choice.

@jonathandavis and I had a discussion about the password being in the email at the time and we determined that since the user's identity is verified by having access to their email, their new password being emailed to them adds no additional security risk as an attacker having access to their email would just be able to reset the password and click the link again anyway. Since the password being emailed is auto-generated it also doesn't introduce any risk of exposing a password the user has reused on other sites.

**Pull request merged**
