### PR TITLE
Renamed shopp('collection.pagination') variables

### PR DESCRIPTION
**Pull request by Just-m**
$jump to $link
$jumps to $jumpsize

### CODE REVIEW

**Comment by meredevelopment** [comment]
Hi, that's good. 

How do you feel about adding more class control thus making pagination styling easier in Bootstrap, Foundation and other frameworks? More args like this: 

```php
'classactive' => `'active',
'classdisabled' => 'disabled',
'classprevious' => 'previous',
'classnext' => 'next'
```
Here's an old PR I did it in: [3365](https://github.com/ingenesis/shopp/pull/3365).

**Comment by Just-m** [comment]
Expressing my personal opinion, I would vote against it. Too much clutter, and the display can already be adjusted with the present classes. 

But, I am not using bootstrap and I have no idea how much we are inclined to adapt to what is useful for bootstrap. If it would error, that would make a difference.

An alternative could be: adding a filter.
Maybe we should vote :)

**Comment by crunnells** [comment]
All of the theme API is filterable via [shopp_themeapi_{object}_{tag}](https://shopplugin.net/api/shopp_themeapi_object_tag/), or in this case, shopp_themeapi_collection_pagination. In theory, this should already be possible.

**Comment by meredevelopment** [comment]
@Just-m @crunnells I would still like to see settable class-names. At the very least I think the main UL class should be settable.

Here's an example of default output in Bootstrap and Foundation (arguable the two biggest layout frameworks?):
image

Here's an example with the UL class set to 'pagination' so that it picks up some of the correct styles. For the output to be perfect it does needs things like 'active' and 'disabled' class to be settable to though:
image

As this is a template-able developer friendly plugin I think that if we set a 'class' anywhere in Theme API code, it should be modifiable at the point the API theme function is called. It's the way we've been going in all the recent API calls. Even if this is filterable it becomes a lot more complex for middle-weight web dev/designer (like myself) to use.

So I obviously vote: Yes :)

**Comment by Just-m** [comment]
What I don't understand is why you need extra classes while classes are already present. Can't you just use those in the stylesheet?

**Comment by crunnells** [comment]
@meredevelopment I'm actually with you on this; we should make it *easy* for developers to skin Shopp, and little things like this go a long way for a very minimal amount of dev time.

**Comment by Just-m** [comment]
If this is implemented I would argue for a different way of using the classnames in the `options`part of the tag. More in sync with other options.

Specify class as an array
`shopp('storefront.pagination', 'show=10&class = array( "class" => "mydefaultclass", "next" => "mynextclass")');`

**Comment by Just-m** [comment]
Maybe it is better to have two options. If you only want to specify the class of the `ul` you use

`shopp('storefront.pagination', 'show=35&class=mypaginationclass');`

and if you want to specify more classes or classes other than the `ul` class you use the array

`shopp('storefront.pagination', 'show=10&class = array( "class" => "mydefaultclass", "next" => "mynextclass")');`

We can check in the codeusing `is_array()` and merge with defaults accordingly.

**Pull request merged**
