### PR TITLE
Minify JavaScript files with Node / NPM / Gulp

### PR DESCRIPTION
**Pull request by clifgriffin**
This adds a simple, light weight, fast, cross platform approach to minifying all JS files. 

Instructions for testing:

0. Install Node https://nodejs.org/en/
1. Change to the current shopp directory.
2. Run `npm install`.
3. Run `npm install -g gulp`
4. Run `gulp`.
5. Change any JS file under `core/ui/*/`

### CODE REVIEW

**Comment by jonathandavis** [comment]
Seems you skipped the download/install npm step.

**Comment by jonathandavis** [comment]
Received this warning when I ran `npm install`:

`shopp@1.4.0 license should be a valid SPDX license expression`

**Comment by clifgriffin** [comment]
Update: The above error was resolved by removing the license parameter.

**Comment by clifgriffin** [comment]
@jonathandavis Do we need to make any modifications to this or can we merge? Ie, are you good with the plan!

**Pull request merged**
