### PR TITLE
Removing mysqli references in ShoppMySQLEngine and DBStorage classes

### PR DESCRIPTION
**Pull request by crunnells**

### CODE REVIEW

**Comment by Just-m** [comment]
I think DBStorage class needs to be patched in a different way. Right now it will error for systems that use `MySQLI`.

I would add `$db = sDB::get();` at the beginning of the function and change the `escape` command to `$data = $db->api->escape($data); `

**Comment by meredevelopment** [comment]
Hi, on holiday with super limited data/coverage, so might have missed the point. But please don't remove mysqli interoperativity (might be a made-up word). 
Several of my servers only have mysqli, and sure this would break them yea?

**Comment by Just-m** [comment]
There are three spots in /core/flow/Install.php that need to be addressed the same way.

**Comment by crunnells** [comment]
Clif fixed it this morning, see commit 64c4df

**Pull request closed without merging**
