### PR TITLE
Collection pagination fixes

### PR DESCRIPTION
**Pull request by msigley**
Fixed order of shopp pagination links. Added classes to first and last links. Added jumps option for setting jump distance. Added first and last option for setting labels on the first and last links.

### CODE REVIEW

**Comment by meredevelopment** [comment]
Nice! Added or a site and works lovely like! +1

**Comment by msigley** [comment]
Fixes #3419.

**Comment by msigley** [comment]
@meredevelopment I made a few other fixes. Mind testing for me again on your install?

**Comment by meredevelopment** [comment]
Morning. Before updating I checked 27eb5e1 again for the problems you fixed in 8689e84 and 5a1be64 and wasn't able to see a problem anyway, I can't see a 'last' class anywhere and last link was showing on next to last page. It might be that you're using an option that I'm not. Here's my args:

```php
'show' => 6,
'label' => "",
'before' => '<nav>',
'after' => '</nav>',
'jumpback' => '&laquo;',
'jumpfwd' => '&raquo;',
'previous' => '&lsaquo;',
'next' => '&rsaquo;',
'class' => 'pagination'
```

Alas, I've added your lastest fixes and it still looks good 👍

**Comment by msigley** [comment]
@meredevelopment: I specifically ran into these issues trying to use this for mobile pagination with 1 page showing.

**Comment by meredevelopment** [comment]
I can't see why that would have been removed either. I think those args are only used as link text so could be arrows or a number.

**Comment by Just-m** [comment]
In the default category template file the code is present as

 `shopp( 'collection.pagination', 'show=10&before=<div class="alignright">' )`
and
`shopp( 'collection.pagination', 'show=10' )`

Removing the default settings will break this code for many.

**Pull request merged**
