### PR TITLE
Fixes suggest js script conflict. This is commonly caused by a global…

### PR DESCRIPTION
**Pull request by msigley**
… admin script_enqueue in bbpress.

### CODE REVIEW

**Comment by clifgriffin** [comment]
@msigley I'd rather us rename our script handle, unless we are using the exact same script as bbpress?

**Comment by msigley** [comment]
@clifgriffin: suggest.js is a Wordpress core script @jonathandavis built upon to add extra features like json support. The issue occurs when both the core and shopp's suggest.js are enqueued on the same page. 
The only other thing we can do besides dequeue the core suggest.js on the shopp admin pages, is to re-namespace all of the functions and global variables in shopp's suggest.js, which I don't think is worth the time invested as I think we should replace this script with a selectize.js textbox anyway. Selectize.js is already used in other Shopp admin screens already as well.

**Comment by clifgriffin** [comment]
@msigley Yeah, that or we need to use the native script. The wall of separation between WP pages and Shopp pages is coming down, and this will be more of an issue.

**Comment by jonathandavis** [comment]
I'd like to factor it out using selectize.js where possible.

**Pull request closed without merging**
