### PR TITLE
Changed custom product and order inputs to be filtered by nl2br

### PR DESCRIPTION
**Pull request by WazzaJB**
Pull request pending suggestion #3174

### CODE REVIEW

**Comment by jonathandavis** [comment]
We really need to discuss this one. I like the suggestion, but I feel we need to discuss the impact of the change. There are likely, now, lots of sites that are setup to work around the `wpautop` formatting.

Can we think of any use-cases where switching to `nl2br` really breaks a site?

**Comment by clifgriffin** [comment]
This should be tested thoroughly. I've seen a lot of pain from nl2br with other theme's/plugins that use it.

Doesn't mean this would also suffer, but I think it warrants caution.

**Comment by clifgriffin** [comment]
@WazzaJB It looks like this PR is now in conflict, possibly because of some rebasing done to master. 

Can you explain better how `wpautop` is causing problems for you? I've never seen an issue with this personally. nl2br is an equally opinionated approach, but one that provides far fewer options for overriding with CSS. 

So, my gut is that we should leave it alone and let devs remove the wpautop filter if they dislike it enough. 

Thoughts?

**Comment by WazzaJB** [comment]
I'm happy for it to stay how it is, I agree that this is an entirely
opinionated argument I just wanted to put the conversation out there to see
how everyone felt about it.

I personally don't believe that (by default) custom inputs should be
displayed in a block element as it forces them onto a new line, when (I
believe) the majority of use case for custom inputs is single line data.

I'm happy to continue filtering this based on my needs, Shopps
extendability let's me do what I like anyway :)

**Comment by jonathandavis** [comment]
I'm closing for now. The discussion is logged and we can always return to it if there is enough developer/user demand.

**Pull request closed without merging**
