### PR TITLE
Adding auto recalculation to cart.js

### PR DESCRIPTION
**Pull request by dxdc**
Automatically fire a recalculation if cart quantities are updated. Note `cart.min.js` needs to be updated also.

https://github.com/ingenesis/shopp/issues/3487

### CODE REVIEW

**Comment by dxdc** [comment]
@sierrab123 thx -- did you run the gulp script on this to generate the minified `cart.min.js`?

**Comment by sierrab123** [comment]
@dxdc Never run one in my sheltered life...

**Comment by dxdc** [comment]
OK :) I can do it later. I only saw `gulpfile.js` after I made these changes.

Essentially, you'll need to do the following:
- Install node/npm (https://nodejs.org/en/download/)
- Install gulp (https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md)
- Run `gulp gulpfile.js`

**Comment by dxdc** [comment]
Created a new PR for those updates @sierrab123

**Pull request merged**
